// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpu5q2RLI_NiMIsYam8eei-bipB6krQQI',
    appId: '1:102495051406:web:b3a2478205f6ec643df3df',
    messagingSenderId: '102495051406',
    projectId: 'read-tracker-3e70d',
    authDomain: 'read-tracker-3e70d.firebaseapp.com',
    storageBucket: 'read-tracker-3e70d.firebasestorage.app',
    measurementId: 'G-GQ7V4QCD7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdowcSKDO15UBb-Z_1S94BWt_pfnbcYsk',
    appId: '1:102495051406:android:74a53b4521c84c973df3df',
    messagingSenderId: '102495051406',
    projectId: 'read-tracker-3e70d',
    storageBucket: 'read-tracker-3e70d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf-YJFYKnI1CEkPAISLIc6NTRJjzRFGh8',
    appId: '1:102495051406:ios:966d8618399eed963df3df',
    messagingSenderId: '102495051406',
    projectId: 'read-tracker-3e70d',
    storageBucket: 'read-tracker-3e70d.firebasestorage.app',
    iosBundleId: 'com.example.readTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf-YJFYKnI1CEkPAISLIc6NTRJjzRFGh8',
    appId: '1:102495051406:ios:966d8618399eed963df3df',
    messagingSenderId: '102495051406',
    projectId: 'read-tracker-3e70d',
    storageBucket: 'read-tracker-3e70d.firebasestorage.app',
    iosBundleId: 'com.example.readTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpu5q2RLI_NiMIsYam8eei-bipB6krQQI',
    appId: '1:102495051406:web:ba2f5fe88d55b2eb3df3df',
    messagingSenderId: '102495051406',
    projectId: 'read-tracker-3e70d',
    authDomain: 'read-tracker-3e70d.firebaseapp.com',
    storageBucket: 'read-tracker-3e70d.firebasestorage.app',
    measurementId: 'G-PQ6XPVY78H',
  );

}